name: Build Android App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18 # Using a super stable version for NativeScript

    - name: Install Mobile Build Tools
      run: npm install -g nativescript

    - name: Install Project Dependencies
      run: npm install --legacy-peer-deps # This stops the installer from failing!

    - name: Build Android APK
      run: ns build android --release --copy-to build.apk

    - name: Upload Finished App
      uses: actions/upload-artifact@v4
      with:
        name: my-android-app
        path: build.apk
